### ISSUE TITLE
Multiple instances on a single connection

### ISSUE THREAD

**Issue by smannering** [PTMagicians/PTMagic#11]
I run 2 instances of PT on a single PC, it would be good if PT Magic could share the CMC data instead of downloading it twice, chewing up bandwidth and data.

**Comment by HojouFotytu** [comment]
Just thinking about this, but this would require quite a bit of modification to work.  It would have to be based on flags/settings in the analyzer file for trends using CMC data, as well as changes to the code to allow the user to specify a new directory...  and then skip the download.

In general, we are trying to get away from relying on outside resources for basic functionality, since they can change unexpectedly, and cause unforeseen issues outside of our control.
