### ISSUE TITLE
Sales overview percentages don't add up correctly

### ISSUE THREAD

**Issue by djbadders** [PTMagicians/PTMagic#161]
**Describe the bug**
The sales overview section in the bottom right doesn't seem to add up; I had started a new test bot and it had been running 2 days with 0.01% made the first day and 0.16% the second day, but the 7 day, 30 day and total rows showed 0.23% instead of 0.17% as expected.

**Expected behavior**
Values of of 0.17%, as 0.1% and 0.16% added equals 0.17%

**Screenshots**
![image](https://user-images.githubusercontent.com/34887832/67437656-4a0c0e80-f5e9-11e9-80b6-fed73f4d7395.png)

**Comment by HojouFotytu** [comment]
Daily gain percentages don't add up that way.  It's not a running total.   

It's a percent gain on your TCV for that period.

Without knowing your TCV it's hard to show the math, but:

So, Yesterday you made .58 which is a .01% gaon on your TCV.
Today you made 19.54 which is .16% gain on your TCV.

In the past week, you made 20.12, which is a .23% gain on your TCV.

**Comment by HojouFotytu** [comment]
Percentages don't add up that way.   It's not a running total.   
It's a percent gain on whatever your TCV was at the start of that period.  This is based on snapshot of your cash balance and the value of any bags you are holding at that time.

Without knowing your TCV at that start of each of those periods, it's hard to check the math.

But the percentages aren't cumulative.

Yesterday you made .58 which is a .01% gain on your TCV at the start of that day.  (You actually made less than .01% -- it's just that PTM doesn't show percentages beyond 2 decimal places.)  

Today you made 19.54 which is .16% gain on your TCV at that start of today.

In the past week, you made 20.12, which is a .23% gain on your TCV -- in this case it would be your strarting balance.

**Comment by HojouFotytu** [comment]
Percentages don't add up that way.   It's not a running total.   It's a percent gain on the current value of your portfolio (TCV), at the start of that period.  

Without knowing your TCV at that start of each of those periods, it's hard to check the math.  But the percentages aren't (and shouldn't be) cumulative.

Yesterday you made .58 which is a .01% gain on your TCV at the start of that day.  (You actually made less than .01% -- it's just that PTM doesn't show percentages beyond 2 decimal places.)  

Today you made 19.54 which is .16% gain on your TCV at that start of today.

And in the past week, you made 20.12, which is a .23% gain on your TCV, which should be your starting balance.  It is NOT a total of each day's percent gain for the past seven days.

So even though your 14 sales today are a gain of .23% of your starting balance, it's only a .16% gain on your TCV at the start of today, due to whatever bags you are holding affecting your TCV.

**Comment by HojouFotytu** [comment]
Percentages don't add up that way.   It's not a running total.   It's realized gains on the current value of your portfolio (TCV), at the start of that period.  

Without knowing your TCV at that start of each of those periods, it's hard to check the math.  But the percentages aren't (and shouldn't be) cumulative.

Yesterday you made .58 which is a .01% gain on your TCV at the start of that day.  (You actually made less than .01% -- it's just that PTM doesn't show percentages beyond 2 decimal places.)  

Today you made 19.54 which is .16% gain on your TCV at that start of today.

And in the past week, you made 20.12, which is a .23% gain on your starting balance.  

So even though your 14 sales today are a gain of .23% of your starting balance, it's only a .16% gain on your TCV at the start of today, due to whatever bags you are holding affecting your TCV.

The 7day, 30day, and Total are NOT a cumulative total of each day's realized gains over that period.  It is a gain on whatever your portfolio value was at the start of that period.  And that will always be different due to prior realized gains and the value of whatever bags you happen to be holding.

**Comment by HojouFotytu** [comment]
Percentages don't add up that way.   It's not a running total.   It's net realized gains on the value of your portfolio (TCV) at the start of that period.  

Without knowing your TCV at that start of each of those periods, it's hard to check the math.  But the percentages aren't (and never should be) cumulative.

Yesterday you made .58 which is a .01% gain on your TCV at the start of that day.  (You actually made less than .01% -- it's just that PTM doesn't show percentages beyond 2 decimal places.)  Today you made 19.54 which is .16% gain on your TCV at that start of today.  And in the past week, you made 20.12, which is a .23% gain on your starting balance.   Even though your 14 sales today are a gain of .23% of your starting balance, it's only a .16% gain on your TCV at the start of today.

So i can assume whatever bags you were holding at the start of Today, before they sold, their total value must have been positive.  This made your TCV higher at the start of Today than your starting balance 7 days ago.  Which is why the %gain Today is lower than the %gain for 7days -- 20.12 is a smaller percentage of a bigger number.

So, the 7day, 30day, and Total are NOT a cumulative total of each day's realized gains over that period.  It is the net gains on the value of your portfolio (TCV) for that period.  And your TCV will always be changing due to the value of whatever bags you happen to be holding as well as prior realized gains and losses.

For example, if your starting balance is $100, and you buy a coin for $100, and sell it for $200, that's a  %100 gain on your cost basis AND your portfolio value.  Imagine you do the same the following day, and buy another coin for $100 and sell it for $200. Again you made %100 on the cost basis for that transaction, but your portfolio gain on day 2 is only %50 -- you made $100 on a portfolio that was worth $200 at the start of the day.  The net gain on your portfolio for the entire two-day period is %200, not the sum of the two days (%100 and %50).  You started with $100, and after two days you have $300. That's a %200 gain on your TCV at the start of the two-day period.

Just as there is a difference between gains on individual transactions that use your cost basis for that transaction and the net percentage gain on your portfolio -- there is also a difference between net percentage gains on your portfolio for individual days and net percentage gain on your portfolio value over a period of days.  You can't just add up the individual days.

For example, notice your daily percent gain/loss is not a total of the gain/loss for every individual sale -- it is the percentage of your total gains that day compared to your portfolio value.  It is the same when calculating gains for individual days over a week - they aren't just added up to calculate your total gains for the week.  Percentage gains for any period are the net value of your gains for that period compared to the value of your portfolio at the start of that period. 

However, we could another column to the total sales figures to show net gains using cost basis, and then people could see the difference.  We would have to calculate the net cost basis for each period (this would be the total purchase price for every transaction on the daily, weekly, and monthly timeframe), and then calculate the net gain/loss on that number.  Most trading software does show this number.  And we could continue to show the net gain/loss as a percentage of the total portfolio value (which is what I think most people are interested in anyway).

If you would like to come up with the code to pull total buy and sell values from PT for those periods, we could add the cost basis and net percent gain for those periods.  I think it would actually be a nice addition.

A first step, though, might be to update the title and tooltip for the total %gain column to make it more clear to users what that number actually represents.  ;)

**Comment by djbadders** [comment]
Thanks for the info
